// Generated by the protocol buffer compiler.  DO NOT EDIT!

package jbr.proto;

public final class Proto2Example {
  private Proto2Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class sample extends
      com.google.protobuf.GeneratedMessage {
    // Use sample.newBuilder() to construct.
    private sample() {}
    
    private static final sample defaultInstance = new sample();
    public static sample getDefaultInstance() {
      return defaultInstance;
    }
    
    public sample getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jbr.proto.Proto2Example.internal_static_com_clv_proto2_sample_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jbr.proto.Proto2Example.internal_static_com_clv_proto2_sample_fieldAccessorTable;
    }
    
    // required string name = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required string address = 2;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    public static jbr.proto.Proto2Example.sample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jbr.proto.Proto2Example.sample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(jbr.proto.Proto2Example.sample prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using jbr.proto.Proto2Example.sample.newBuilder()
      private Builder() {}
      
      jbr.proto.Proto2Example.sample result = new jbr.proto.Proto2Example.sample();
      
      @Override
      protected jbr.proto.Proto2Example.sample internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new jbr.proto.Proto2Example.sample();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jbr.proto.Proto2Example.sample.getDescriptor();
      }
      
      public jbr.proto.Proto2Example.sample getDefaultInstanceForType() {
        return jbr.proto.Proto2Example.sample.getDefaultInstance();
      }
      
      public jbr.proto.Proto2Example.sample build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private jbr.proto.Proto2Example.sample buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public jbr.proto.Proto2Example.sample buildPartial() {
        jbr.proto.Proto2Example.sample returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // required string address = 2;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = "";
        return this;
      }
    }
    
    static {
      jbr.proto.Proto2Example.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_clv_proto2_sample_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_clv_proto2_sample_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\rsample2.proto\022\016com.clv.proto2\"\'\n\006sampl" +
      "e\022\014\n\004name\030\001 \002(\t\022\017\n\007address\030\002 \002(\tB\032\n\tjbr." +
      "protoB\rProto2Example";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_clv_proto2_sample_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_clv_proto2_sample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_clv_proto2_sample_descriptor,
              new java.lang.String[] { "Name", "Address", },
              jbr.proto.Proto2Example.sample.class,
              jbr.proto.Proto2Example.sample.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
