// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package jbr.java.protobuf;

public final class EmployeeDetails {
  private EmployeeDetails() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code protobuf.Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Employee)
      EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      id_ = 0;
      email_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jbr.java.protobuf.EmployeeDetails.Employee.class, jbr.java.protobuf.EmployeeDetails.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jbr.java.protobuf.EmployeeDetails.Employee)) {
        return super.equals(obj);
      }
      jbr.java.protobuf.EmployeeDetails.Employee other = (jbr.java.protobuf.EmployeeDetails.Employee) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasEmail() == other.hasEmail());
      if (hasEmail()) {
        result = result && getEmail()
            .equals(other.getEmail());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jbr.java.protobuf.EmployeeDetails.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Employee)
        jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jbr.java.protobuf.EmployeeDetails.Employee.class, jbr.java.protobuf.EmployeeDetails.Employee.Builder.class);
      }

      // Construct using jbr.java.protobuf.EmployeeDetails.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_Employee_descriptor;
      }

      public jbr.java.protobuf.EmployeeDetails.Employee getDefaultInstanceForType() {
        return jbr.java.protobuf.EmployeeDetails.Employee.getDefaultInstance();
      }

      public jbr.java.protobuf.EmployeeDetails.Employee build() {
        jbr.java.protobuf.EmployeeDetails.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jbr.java.protobuf.EmployeeDetails.Employee buildPartial() {
        jbr.java.protobuf.EmployeeDetails.Employee result = new jbr.java.protobuf.EmployeeDetails.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jbr.java.protobuf.EmployeeDetails.Employee) {
          return mergeFrom((jbr.java.protobuf.EmployeeDetails.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jbr.java.protobuf.EmployeeDetails.Employee other) {
        if (other == jbr.java.protobuf.EmployeeDetails.Employee.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jbr.java.protobuf.EmployeeDetails.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jbr.java.protobuf.EmployeeDetails.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Employee)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Employee)
    private static final jbr.java.protobuf.EmployeeDetails.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jbr.java.protobuf.EmployeeDetails.Employee();
    }

    public static jbr.java.protobuf.EmployeeDetails.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    public jbr.java.protobuf.EmployeeDetails.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeeDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.EmployeeData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    java.util.List<jbr.java.protobuf.EmployeeDetails.Employee> 
        getEmployeeList();
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    jbr.java.protobuf.EmployeeDetails.Employee getEmployee(int index);
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    int getEmployeeCount();
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    java.util.List<? extends jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder> 
        getEmployeeOrBuilderList();
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder getEmployeeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.EmployeeData}
   */
  public  static final class EmployeeData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.EmployeeData)
      EmployeeDataOrBuilder {
    // Use EmployeeData.newBuilder() to construct.
    private EmployeeData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmployeeData() {
      employee_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmployeeData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                employee_ = new java.util.ArrayList<jbr.java.protobuf.EmployeeDetails.Employee>();
                mutable_bitField0_ |= 0x00000001;
              }
              employee_.add(
                  input.readMessage(jbr.java.protobuf.EmployeeDetails.Employee.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          employee_ = java.util.Collections.unmodifiableList(employee_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_EmployeeData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_EmployeeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jbr.java.protobuf.EmployeeDetails.EmployeeData.class, jbr.java.protobuf.EmployeeDetails.EmployeeData.Builder.class);
    }

    public static final int EMPLOYEE_FIELD_NUMBER = 1;
    private java.util.List<jbr.java.protobuf.EmployeeDetails.Employee> employee_;
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    public java.util.List<jbr.java.protobuf.EmployeeDetails.Employee> getEmployeeList() {
      return employee_;
    }
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    public java.util.List<? extends jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder> 
        getEmployeeOrBuilderList() {
      return employee_;
    }
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    public int getEmployeeCount() {
      return employee_.size();
    }
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    public jbr.java.protobuf.EmployeeDetails.Employee getEmployee(int index) {
      return employee_.get(index);
    }
    /**
     * <code>repeated .protobuf.Employee employee = 1;</code>
     */
    public jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder getEmployeeOrBuilder(
        int index) {
      return employee_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getEmployeeCount(); i++) {
        if (!getEmployee(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < employee_.size(); i++) {
        output.writeMessage(1, employee_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < employee_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, employee_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jbr.java.protobuf.EmployeeDetails.EmployeeData)) {
        return super.equals(obj);
      }
      jbr.java.protobuf.EmployeeDetails.EmployeeData other = (jbr.java.protobuf.EmployeeDetails.EmployeeData) obj;

      boolean result = true;
      result = result && getEmployeeList()
          .equals(other.getEmployeeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmployeeCount() > 0) {
        hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jbr.java.protobuf.EmployeeDetails.EmployeeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jbr.java.protobuf.EmployeeDetails.EmployeeData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.EmployeeData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.EmployeeData)
        jbr.java.protobuf.EmployeeDetails.EmployeeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_EmployeeData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_EmployeeData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jbr.java.protobuf.EmployeeDetails.EmployeeData.class, jbr.java.protobuf.EmployeeDetails.EmployeeData.Builder.class);
      }

      // Construct using jbr.java.protobuf.EmployeeDetails.EmployeeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmployeeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (employeeBuilder_ == null) {
          employee_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          employeeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jbr.java.protobuf.EmployeeDetails.internal_static_protobuf_EmployeeData_descriptor;
      }

      public jbr.java.protobuf.EmployeeDetails.EmployeeData getDefaultInstanceForType() {
        return jbr.java.protobuf.EmployeeDetails.EmployeeData.getDefaultInstance();
      }

      public jbr.java.protobuf.EmployeeDetails.EmployeeData build() {
        jbr.java.protobuf.EmployeeDetails.EmployeeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jbr.java.protobuf.EmployeeDetails.EmployeeData buildPartial() {
        jbr.java.protobuf.EmployeeDetails.EmployeeData result = new jbr.java.protobuf.EmployeeDetails.EmployeeData(this);
        int from_bitField0_ = bitField0_;
        if (employeeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            employee_ = java.util.Collections.unmodifiableList(employee_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employee_ = employee_;
        } else {
          result.employee_ = employeeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jbr.java.protobuf.EmployeeDetails.EmployeeData) {
          return mergeFrom((jbr.java.protobuf.EmployeeDetails.EmployeeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jbr.java.protobuf.EmployeeDetails.EmployeeData other) {
        if (other == jbr.java.protobuf.EmployeeDetails.EmployeeData.getDefaultInstance()) return this;
        if (employeeBuilder_ == null) {
          if (!other.employee_.isEmpty()) {
            if (employee_.isEmpty()) {
              employee_ = other.employee_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeeIsMutable();
              employee_.addAll(other.employee_);
            }
            onChanged();
          }
        } else {
          if (!other.employee_.isEmpty()) {
            if (employeeBuilder_.isEmpty()) {
              employeeBuilder_.dispose();
              employeeBuilder_ = null;
              employee_ = other.employee_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmployeeFieldBuilder() : null;
            } else {
              employeeBuilder_.addAllMessages(other.employee_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEmployeeCount(); i++) {
          if (!getEmployee(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jbr.java.protobuf.EmployeeDetails.EmployeeData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jbr.java.protobuf.EmployeeDetails.EmployeeData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<jbr.java.protobuf.EmployeeDetails.Employee> employee_ =
        java.util.Collections.emptyList();
      private void ensureEmployeeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          employee_ = new java.util.ArrayList<jbr.java.protobuf.EmployeeDetails.Employee>(employee_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jbr.java.protobuf.EmployeeDetails.Employee, jbr.java.protobuf.EmployeeDetails.Employee.Builder, jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder> employeeBuilder_;

      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public java.util.List<jbr.java.protobuf.EmployeeDetails.Employee> getEmployeeList() {
        if (employeeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employee_);
        } else {
          return employeeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public int getEmployeeCount() {
        if (employeeBuilder_ == null) {
          return employee_.size();
        } else {
          return employeeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public jbr.java.protobuf.EmployeeDetails.Employee getEmployee(int index) {
        if (employeeBuilder_ == null) {
          return employee_.get(index);
        } else {
          return employeeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder setEmployee(
          int index, jbr.java.protobuf.EmployeeDetails.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.set(index, value);
          onChanged();
        } else {
          employeeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder setEmployee(
          int index, jbr.java.protobuf.EmployeeDetails.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder addEmployee(jbr.java.protobuf.EmployeeDetails.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.add(value);
          onChanged();
        } else {
          employeeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder addEmployee(
          int index, jbr.java.protobuf.EmployeeDetails.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeeIsMutable();
          employee_.add(index, value);
          onChanged();
        } else {
          employeeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder addEmployee(
          jbr.java.protobuf.EmployeeDetails.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.add(builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder addEmployee(
          int index, jbr.java.protobuf.EmployeeDetails.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder addAllEmployee(
          java.lang.Iterable<? extends jbr.java.protobuf.EmployeeDetails.Employee> values) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employee_);
          onChanged();
        } else {
          employeeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder clearEmployee() {
        if (employeeBuilder_ == null) {
          employee_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public Builder removeEmployee(int index) {
        if (employeeBuilder_ == null) {
          ensureEmployeeIsMutable();
          employee_.remove(index);
          onChanged();
        } else {
          employeeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public jbr.java.protobuf.EmployeeDetails.Employee.Builder getEmployeeBuilder(
          int index) {
        return getEmployeeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder getEmployeeOrBuilder(
          int index) {
        if (employeeBuilder_ == null) {
          return employee_.get(index);  } else {
          return employeeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public java.util.List<? extends jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder> 
           getEmployeeOrBuilderList() {
        if (employeeBuilder_ != null) {
          return employeeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employee_);
        }
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public jbr.java.protobuf.EmployeeDetails.Employee.Builder addEmployeeBuilder() {
        return getEmployeeFieldBuilder().addBuilder(
            jbr.java.protobuf.EmployeeDetails.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public jbr.java.protobuf.EmployeeDetails.Employee.Builder addEmployeeBuilder(
          int index) {
        return getEmployeeFieldBuilder().addBuilder(
            index, jbr.java.protobuf.EmployeeDetails.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Employee employee = 1;</code>
       */
      public java.util.List<jbr.java.protobuf.EmployeeDetails.Employee.Builder> 
           getEmployeeBuilderList() {
        return getEmployeeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jbr.java.protobuf.EmployeeDetails.Employee, jbr.java.protobuf.EmployeeDetails.Employee.Builder, jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder> 
          getEmployeeFieldBuilder() {
        if (employeeBuilder_ == null) {
          employeeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jbr.java.protobuf.EmployeeDetails.Employee, jbr.java.protobuf.EmployeeDetails.Employee.Builder, jbr.java.protobuf.EmployeeDetails.EmployeeOrBuilder>(
                  employee_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          employee_ = null;
        }
        return employeeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.EmployeeData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.EmployeeData)
    private static final jbr.java.protobuf.EmployeeDetails.EmployeeData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jbr.java.protobuf.EmployeeDetails.EmployeeData();
    }

    public static jbr.java.protobuf.EmployeeDetails.EmployeeData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EmployeeData>
        PARSER = new com.google.protobuf.AbstractParser<EmployeeData>() {
      public EmployeeData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EmployeeData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmployeeData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeData> getParserForType() {
      return PARSER;
    }

    public jbr.java.protobuf.EmployeeDetails.EmployeeData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_EmployeeData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_EmployeeData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\010protobuf\"3\n\010Employee\022\014" +
      "\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t\"" +
      "4\n\014EmployeeData\022$\n\010employee\030\001 \003(\0132\022.prot" +
      "obuf.EmployeeB$\n\021jbr.java.protobufB\017Empl" +
      "oyeeDetails"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Employee_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", });
    internal_static_protobuf_EmployeeData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_EmployeeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_EmployeeData_descriptor,
        new java.lang.String[] { "Employee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
